# Generated by Django 4.2.11 on 2024-04-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_market_product_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermanagement',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
