# Generated by Django 4.2.11 on 2024-04-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_market_product_api', '0003_alter_ordermanagement_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
